/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all inventory
         * @description Returns SKUs sorted by skuId, at most 250 per response. When more SKUs follow, the Link header holds the next page's URL; follow it until a response has no Link to list all inventory. If no SKUs exist, returns an empty array.
         */
        get: operations["listInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{skuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get inventory for a SKU */
        get: operations["getInventory"];
        put?: never;
        /** Create or update inventory for a SKU */
        post: operations["createInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{skuId}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purchase a quantity of a SKU */
        post: operations["purchaseItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all SKUs with details
         * @description Returns SKUs sorted by skuId with their quantity and details (absent for a SKU that has none), at most 250 per response; the same limit, after and Link rules as GET /inventory.
         */
        get: operations["listSkus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/inventory/{skuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a SKU with its details */
        get: operations["getSku"];
        /**
         * Replace a SKU's details
         * @description Replaces the SKU's details (creates them for a SKU that has none). Stock is not changed. With If-Match, the details are replaced only when their current ETag is one of the listed values, else 412.
         */
        put: operations["replaceSkuDetails"];
        /**
         * Create a SKU with details
         * @description Creates the SKU with its details and optional initial stock in one transaction; initial stock is recorded in the ledger like an add. A SKU that already exists (including one created by POST /inventory/{skuId}) is 409; set its details with PUT and add stock with POST /inventory/{skuId}.
         */
        post: operations["createSku"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/inventory/{skuId}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create a SKU or replace its details
         * @description Replaces the whole SkuDetails of the SKU. A SKU that does not exist is created with quantity 0 (201, ETag "1"); an existing SKU keeps its stock (200, new ETag). If-Match (strong ETags, or "*" for any existing SKU) and If-None-Match: * (create only) are optional preconditions; without one the PUT is unconditional. Any If-Match on a SKU that does not exist is 412. Idempotency-Key is ignored: PUT is idempotent by method.
         */
        put: operations["putSkuDetails"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSkuRequest: {
            details: components["schemas"]["SkuDetails"];
            /**
             * Format: int32
             * @description Stock to record at creation (absent or null means 0), through the same ledger as an add
             * @default 0
             */
            initialQuantity: number;
        };
        InventoryItem: {
            /** Format: int64 */
            quantity?: number;
            skuId?: string;
        };
        InventoryQuantity: {
            /** Format: int32 */
            quantity: number;
        };
        /** @description A cost in minor units of a currency */
        SkuCost: {
            /**
             * Format: int64
             * @description Minor units (e.g. cents), never negative
             */
            amount: number;
            /** @description Three-letter uppercase currency code */
            currency: string;
        };
        SkuDetails: {
            cost?: components["schemas"]["SkuCost"];
            /** @description Up to 2000 characters (UTF-16 units); newlines and tabs allowed; default "" */
            description?: string;
            /** @description Up to 10 absolute http or https URLs in ASCII (percent-encoded); default [] */
            images?: string[];
            /** @description 1 to 120 characters (UTF-16 units), not blank, no control characters */
            name: string;
        };
        SkuItem: {
            details?: components["schemas"]["SkuDetails"];
            /** Format: int64 */
            quantity: number;
            skuId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listInventory: {
        parameters: {
            query?: {
                /** @description Optional page size, 1 to 250 (default 250). Larger values mean 250; other values are ignored and the default applies. */
                limit?: number;
                /** @description Optional cursor: return only SKUs whose skuId sorts after this value, up to the page size. It must not be repeated. */
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of inventory items, at most 250, sorted by skuId */
            200: {
                headers: {
                    /** @description Next page, when more SKUs follow: <URL>; rel="next" */
                    Link?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"][];
                };
            };
            /** @description Invalid request: the query string can't be decoded or repeats after */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getInventory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current inventory state for the sku */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"];
                };
            };
            /** @description SKU not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    createInventory: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional UUID. The same key with the same request replays the first response. A different request, or a key older than 24h, returns 400. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryQuantity"];
            };
        };
        responses: {
            /** @description Current state of the item after update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    purchaseItem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional UUID. The same key with the same request replays the first response. A different request, or a key older than 24h, returns 400. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryQuantity"];
            };
        };
        responses: {
            /** @description Purchase successful; remaining inventory for the item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"];
                };
            };
            /** @description Insufficient inventory or invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description SKU not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listSkus: {
        parameters: {
            query?: {
                /** @description Optional page size, 1 to 250 (default 250). Larger values mean 250; other values are ignored and the default applies. */
                limit?: number;
                /** @description Optional cursor: return only SKUs whose skuId sorts after this value, up to the page size. It must not be repeated. */
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of SKUs with details, at most 250, sorted by skuId */
            200: {
                headers: {
                    /** @description Next page, when more SKUs follow: <URL>; rel="next" */
                    Link?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuItem"][];
                };
            };
            /** @description Invalid request: the query string can't be decoded or repeats after */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getSku: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The SKU with its quantity and details */
            200: {
                headers: {
                    /** @description The details version, a strong validator for If-Match; "0" before any details */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuItem"];
                };
            };
            /** @description SKU not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    replaceSkuDetails: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional strong ETag(s) from a previous response; "*" or absent means unconditional */
                "If-Match"?: string;
            };
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuDetails"];
            };
        };
        responses: {
            /** @description The SKU after the update */
            200: {
                headers: {
                    /** @description The details version, a strong validator for If-Match; "0" before any details */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuItem"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description SKU not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Details changed since you read them. Reload the SKU and retry with its new ETag. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    createSku: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional UUID. The same key with the same request replays the first response. A different request, or a key older than 24h, returns 400. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSkuRequest"];
            };
        };
        responses: {
            /** @description The created SKU */
            201: {
                headers: {
                    /** @description The details version of a new SKU, always "1" (also on a replayed 201, even after a later PUT) */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuItem"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description SKU already exists. Set its details with PUT /v2/inventory/{skuId}; add stock with POST /inventory/{skuId}. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    putSkuDetails: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional strong ETag(s) from a previous response, or "*" for any existing SKU; 412 when none matches or the SKU does not exist */
                "If-Match"?: string;
                /** @description Optional; only "*" is supported: create only, 412 when the SKU already exists. Any other value is 400 */
                "If-None-Match"?: string;
            };
            path: {
                /** @description SKU ID: 1 to 64 characters; letters, digits, '.', '_' or '-', starting with a letter or digit. Case-sensitive. */
                skuId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkuDetails"];
            };
        };
        responses: {
            /** @description The SKU with its replaced details */
            200: {
                headers: {
                    /** @description The details version, a strong validator for If-Match; "0" before any details */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuItem"];
                };
            };
            /** @description The SKU was created at quantity 0 with these details */
            201: {
                headers: {
                    /** @description The details version of a new SKU, always "1" (also on a replayed 201, even after a later PUT) */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkuItem"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Details changed since you read them. Reload the SKU and retry with its new ETag. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
